[package]
name = "bench"
version = "0.1.0"
authors = ["cyrille-blanchet-1974 <cyrille.blanchet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
